package models;
// Generated 15 nov. 2022 à 14:57:29 by Hibernate Tools 6.1.3.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Article generated by hbm2java
 */
@Entity
@Table(name = "Article", catalog = "kahoueh")
public class Article implements java.io.Serializable {

	private Integer artId;
	private float artPrix;
	private int artStock;
	private String artImg;
	private String artDesc;
	private float artTauxTva;
	private int artMarque;
	private Integer artCategorie;

	public Article() {
	}

	public Article(float artPrix, int artStock, String artImg, String artDesc, float artTauxTva, int artMarque) {
		this.artPrix = artPrix;
		this.artStock = artStock;
		this.artImg = artImg;
		this.artDesc = artDesc;
		this.artTauxTva = artTauxTva;
		this.artMarque = artMarque;
	}

	public Article(float artPrix, int artStock, String artImg, String artDesc, float artTauxTva, int artMarque,
			Integer artCategorie) {
		this.artPrix = artPrix;
		this.artStock = artStock;
		this.artImg = artImg;
		this.artDesc = artDesc;
		this.artTauxTva = artTauxTva;
		this.artMarque = artMarque;
		this.artCategorie = artCategorie;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "artID", unique = true, nullable = false)
	public Integer getArtId() {
		return this.artId;
	}

	public void setArtId(Integer artId) {
		this.artId = artId;
	}

	@Column(name = "artPrix", unique = true, nullable = false)
	public float getArtPrix() {
		return this.artPrix;
	}

	public void setArtPrix(float artPrix) {
		this.artPrix = artPrix;
	}

	@Column(name = "artStock", unique = true, nullable = false)
	public int getArtStock() {
		return this.artStock;
	}

	public void setArtStock(int artStock) {
		this.artStock = artStock;
	}

	@Column(name = "artImg", unique = true, nullable = false)
	public String getArtImg() {
		return this.artImg;
	}

	public void setArtImg(String artImg) {
		this.artImg = artImg;
	}

	@Column(name = "artDesc", unique = true, nullable = false)
	public String getArtDesc() {
		return this.artDesc;
	}

	public void setArtDesc(String artDesc) {
		this.artDesc = artDesc;
	}

	@Column(name = "artTauxTva", unique = true, nullable = false)
	public float getArtTauxTva() {
		return this.artTauxTva;
	}

	public void setArtTauxTva(float artTauxTva) {
		this.artTauxTva = artTauxTva;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity = Marque.class)
	@JoinColumn(name = "artMarque", unique = true, nullable = false)
	public int getArtMarque() {
		return this.artMarque;
	}

	public void setArtMarque(int artMarque) {
		this.artMarque = artMarque;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity = Categorie.class)
	@JoinColumn(name = "artCategorie", unique = true, nullable = false)
	public Integer getArtCategorie() {
		return this.artCategorie;
	}

	public void setArtCategorie(Integer artCategorie) {
		this.artCategorie = artCategorie;
	}

}
