package models;
// Generated 18 nov. 2022 à 13:52:38 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Banque generated by hbm2java
 */
@Entity
@Table(name = "Banque", catalog = "kahoueh")
public class Banque implements java.io.Serializable {

	private int id;
	private String numCarte;
	private String cvc;
	private String expir;
	private float solde;

	public Banque() {
	}

	public Banque(int id, String numCarte, String cvc, String expir, float solde) {
		this.id = id;
		this.numCarte = numCarte;
		this.cvc = cvc;
		this.expir = expir;
		this.solde = solde;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "numCarte", nullable = false)
	public String getNumCarte() {
		return this.numCarte;
	}

	public void setNumCarte(String numCarte) {
		this.numCarte = numCarte;
	}

	@Column(name = "cvc", nullable = false)
	public String getCvc() {
		return this.cvc;
	}

	public void setCvc(String cvc) {
		this.cvc = cvc;
	}

	@Column(name = "expir", nullable = false)
	public String getExpir() {
		return this.expir;
	}

	public void setExpir(String expir) {
		this.expir = expir;
	}

	@Column(name = "solde", nullable = false, precision = 12, scale = 0)
	public float getSolde() {
		return this.solde;
	}

	public void setSolde(float solde) {
		this.solde = solde;
	}

}
