package models;
// Generated 18 nov. 2022 à 13:52:38 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categorie generated by hbm2java
 */
@Entity
@Table(name = "Categorie", catalog = "kahoueh")
public class Categorie implements java.io.Serializable {

	private Integer catId;
	private String catNom;
	private Set<Article> articles = new HashSet<Article>(0);

	public Categorie() {
	}

	public Categorie(String catNom) {
		this.catNom = catNom;
	}

	public Categorie(String catNom, Set<Article> articles) {
		this.catNom = catNom;
		this.articles = articles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "catID", unique = true, nullable = false)
	public Integer getCatId() {
		return this.catId;
	}

	public void setCatId(Integer catId) {
		this.catId = catId;
	}

	@Column(name = "catNom", nullable = false)
	public String getCatNom() {
		return this.catNom;
	}

	public void setCatNom(String catNom) {
		this.catNom = catNom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categorie")
	public Set<Article> getArticles() {
		return this.articles;
	}

	public void setArticles(Set<Article> articles) {
		this.articles = articles;
	}

}
