package models;
// Generated 15 nov. 2022 à 17:36:34 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Categorie generated by hbm2java
 */
@Entity
@Table(name = "Categorie", catalog = "kahoueh")
public class Categorie implements java.io.Serializable {

	private Integer catId;
	private String catNom;

	public Categorie() {
	}

	public Categorie(String catNom) {
		this.catNom = catNom;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "catID", unique = true, nullable = false)
	public Integer getCatId() {
		return this.catId;
	}

	public void setCatId(Integer catId) {
		this.catId = catId;
	}

	@Column(name = "catNom", nullable = false)
	public String getCatNom() {
		return this.catNom;
	}

	public void setCatNom(String catNom) {
		this.catNom = catNom;
	}

}
