package models;
// Generated 15 nov. 2022 à 15:31:58 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Commande generated by hbm2java
 */
@Entity
@Table(name = "Commande", catalog = "kahoueh")
public class Commande implements java.io.Serializable {

	private Integer cmdId;
	private Date cmdDate;
	private float cmdPrix;
	private int cmdNbArt;
	private String cmdDesc;
	private String cmdArticles;
	private int cmdEtat;
	private int cmdUtil;

	public Commande() {
	}

	public Commande(Date cmdDate, float cmdPrix, int cmdNbArt, String cmdDesc, String cmdArticles, int cmdEtat,
			int cmdUtil) {
		this.cmdDate = cmdDate;
		this.cmdPrix = cmdPrix;
		this.cmdNbArt = cmdNbArt;
		this.cmdDesc = cmdDesc;
		this.cmdArticles = cmdArticles;
		this.cmdEtat = cmdEtat;
		this.cmdUtil = cmdUtil;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "cmdID", unique = true, nullable = false)
	public Integer getCmdId() {
		return this.cmdId;
	}

	public void setCmdId(Integer cmdId) {
		this.cmdId = cmdId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "cmdDate", nullable = false, length = 10)
	public Date getCmdDate() {
		return this.cmdDate;
	}

	public void setCmdDate(Date cmdDate) {
		this.cmdDate = cmdDate;
	}

	@Column(name = "cmdPrix", nullable = false, precision = 12, scale = 0)
	public float getCmdPrix() {
		return this.cmdPrix;
	}

	public void setCmdPrix(float cmdPrix) {
		this.cmdPrix = cmdPrix;
	}

	@Column(name = "cmdNbArt", nullable = false)
	public int getCmdNbArt() {
		return this.cmdNbArt;
	}

	public void setCmdNbArt(int cmdNbArt) {
		this.cmdNbArt = cmdNbArt;
	}

	@Column(name = "cmdDesc", nullable = false)
	public String getCmdDesc() {
		return this.cmdDesc;
	}

	public void setCmdDesc(String cmdDesc) {
		this.cmdDesc = cmdDesc;
	}

	@Column(name = "cmdArticles", nullable = false)
	public String getCmdArticles() {
		return this.cmdArticles;
	}

	public void setCmdArticles(String cmdArticles) {
		this.cmdArticles = cmdArticles;
	}

	@Column(name = "cmdEtat", nullable = false)
	public int getCmdEtat() {
		return this.cmdEtat;
	}

	public void setCmdEtat(int cmdEtat) {
		this.cmdEtat = cmdEtat;
	}

	@Column(name = "cmdUtil", nullable = false)
	public int getCmdUtil() {
		return this.cmdUtil;
	}

	public void setCmdUtil(int cmdUtil) {
		this.cmdUtil = cmdUtil;
	}

}
