package models;
// Generated 15 nov. 2022 à 17:36:34 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Facture generated by hbm2java
 */
@Entity
@Table(name = "Facture", catalog = "kahoueh")
public class Facture implements java.io.Serializable {

	private Integer factId;
	private Date factDate;
	private float factHt;
	private float factTva;
	private float factTtc;

	public Facture() {
	}

	public Facture(Date factDate, float factHt, float factTva, float factTtc) {
		this.factDate = factDate;
		this.factHt = factHt;
		this.factTva = factTva;
		this.factTtc = factTtc;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "factID", unique = true, nullable = false)
	public Integer getFactId() {
		return this.factId;
	}

	public void setFactId(Integer factId) {
		this.factId = factId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "factDate", nullable = false, length = 10)
	public Date getFactDate() {
		return this.factDate;
	}

	public void setFactDate(Date factDate) {
		this.factDate = factDate;
	}

	@Column(name = "factHT", nullable = false, precision = 12, scale = 0)
	public float getFactHt() {
		return this.factHt;
	}

	public void setFactHt(float factHt) {
		this.factHt = factHt;
	}

	@Column(name = "factTVA", nullable = false, precision = 12, scale = 0)
	public float getFactTva() {
		return this.factTva;
	}

	public void setFactTva(float factTva) {
		this.factTva = factTva;
	}

	@Column(name = "factTTC", nullable = false, precision = 12, scale = 0)
	public float getFactTtc() {
		return this.factTtc;
	}

	public void setFactTtc(float factTtc) {
		this.factTtc = factTtc;
	}

}
