package models;
// Generated 15 nov. 2022 à 17:36:34 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Marque generated by hbm2java
 */
@Entity
@Table(name = "Marque", catalog = "kahoueh")
public class Marque implements java.io.Serializable {

	private Integer marqueId;
	private String marqueNom;

	public Marque() {
	}

	public Marque(String marqueNom) {
		this.marqueNom = marqueNom;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "marqueID", unique = true, nullable = false)
	public Integer getMarqueId() {
		return this.marqueId;
	}

	public void setMarqueId(Integer marqueId) {
		this.marqueId = marqueId;
	}

	@Column(name = "marqueNom", nullable = false)
	public String getMarqueNom() {
		return this.marqueNom;
	}

	public void setMarqueNom(String marqueNom) {
		this.marqueNom = marqueNom;
	}

}
